// Generate a DESIGN.md in the awesome-claude-design 9-section format from a brand brief.
// The output is a single markdown document the downstream skills will consume as the
// brand contract for every artifact (landing page, deck, etc.).
export function designSystemPrompt(brief: string): string {
  return [
    "You are writing a brand design system (DESIGN.md) for a new brand. The strategy is finished. Translate it into concrete visual decisions.",
    "",
    "Use the following 9-section format exactly. Be specific: name exact hex colors, font families, spacing tokens, and interaction rules. Do not hedge or use placeholder language. Every decision must trace back to the strategy below.",
    "",
    "```markdown",
    "# <Brand Name>",
    "",
    "## Visual Theme & Atmosphere",
    "2-3 sentences describing the overall mood, art direction, and first impression. One concrete analogy (a place, material, era, or natural phenomenon) is required.",
    "",
    "## Color Palette & Roles",
    "Primary, secondary, accent, background, surface, text, muted, success, warning, danger. For each: hex code, CSS variable name, and exact role (what it is used for). No more than 6 core colors plus semantic colors.",
    "",
    "## Typography Rules",
    "Heading font family, body font family, mono font family (if any). Fallback stacks. Font sizes in rem/px for hero, h1, h2, h3, body, small, caption. Line heights and letter-spacing. Font weights. Max line length for readability.",
    "",
    "## Component Stylings",
    "Buttons: shape, padding, color combinations for primary/secondary/ghost, hover state, disabled state. Cards: radius, shadow, padding, border. Inputs: height, border, focus ring. Links: default and hover style. Badges/tags: style.",
    "",
    "## Layout Principles",
    "Max content width, page padding values, grid columns, section spacing, spacing scale (e.g. 4px base). When to use centered vs. asymmetric layouts. Navigation placement rules.",
    "",
    "## Depth & Elevation",
    "Shadow scale (none/small/medium/large), when to use each. Border rules. Use of blur/backdrop. Layer order (z-index) rules.",
    "",
    "## Do's and Don'ts",
    "5-7 concrete visual rules: what the brand always does, and what it never does. E.g. 'Never use gradients on text', 'Always leave generous whitespace', 'Never use stock photography of people', etc.",
    "",
    "## Responsive Behavior",
    "Breakpoints. How the type scale collapses. How layouts adapt. Touch target minimum sizes. Mobile navigation behavior.",
    "",
    "## Agent Prompt Guide",
    "A short paragraph telling any design agent how to use this system: what to prioritize, what to avoid, and the one sentence that captures the brand's visual personality.",
    "```",
    "",
    "Return ONLY the markdown file contents. No explanatory prose, no code fences around the whole document.",
    "",
    "THE BRAND STRATEGY:",
    brief,
  ].join("\n");
}

// Generate a single-file, self-contained landing page HTML artifact.
// The output must be a complete HTML file with inline CSS and no external dependencies.
export function landingPagePrompt(brief: string, designSystem: string): string {
  return [
    "You are building a single-page brand landing page as a complete, self-contained HTML file. The brand strategy and design system are provided below.",
    "",
    "Requirements:",
    "- One single HTML file with all CSS inlined in a <style> tag.",
    "- Use ONLY the colors, fonts, and spacing defined in the DESIGN.md. No generic #6366f1 indigo defaults. No placeholder images unless you use a solid-color CSS block with a label.",
    "- Sections: sticky navigation, hero (name + value proposition + CTA), problem, solution, brand promise / manifesto excerpt, ideal client, CTA, footer.",
    "- Copy must be real, specific, and based on the brief. No lorem ipsum. No 'revolutionary' or 'seamless' filler.",
    "- Responsive: works on mobile and desktop.",
    "- Use semantic HTML and clean, readable CSS. No JavaScript required.",
    "- Include a small design-credit comment in the footer like 'Generated by Brand App'.",
    "",
    "Return ONLY the complete HTML file contents, starting with <!DOCTYPE html> and ending with </html>. No markdown code fences, no explanation.",
    "",
    "DESIGN SYSTEM:",
    designSystem,
    "",
    "BRAND STRATEGY:",
    brief,
  ].join("\n");
}

// Generate a single-file HTML brand deck / pitch deck for client review or handoff.
export function brandDeckPrompt(brief: string, designSystem: string): string {
  return [
    "You are building a brand presentation deck as a single HTML file with inline CSS. The deck is navigated by arrow keys or on-screen buttons. Each slide is a full viewport section.",
    "",
    "Requirements:",
    "- One single HTML file with all CSS and JS inlined.",
    "- Use ONLY the design system colors, fonts, and spacing.",
    "- Slides (in order): Title + concept, Problem, Solution, Brand Promise, Personality & Tone, Visual Direction, Color & Type, Application (landing page / touchpoint), Next Steps.",
    "- Copy is specific to the brand. No lorem ipsum, no generic filler.",
    "- Add simple keyboard navigation: left/right arrow keys and on-screen buttons to change slides.",
    "- Responsive: readable on a laptop screen.",
    "",
    "Return ONLY the complete HTML file contents, starting with <!DOCTYPE html> and ending with </html>. No markdown code fences, no explanation.",
    "",
    "DESIGN SYSTEM:",
    designSystem,
    "",
    "BRAND STRATEGY:",
    brief,
  ].join("\n");
}
